version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8081}:8080"
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - ./static:/app/static
      - ./views:/app/views
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
