version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sersoft
      - MYSQL_HOST=190.171.167.226
      - MYSQL_DATABASE=BDCrispieri2019
      - SQLSERVER_CONNECTION_STRING=server=190.171.167.226;user id=VENTAS2;password=Sersoft123*;database=BDMCrispieri2
    networks:
      - app-network
    volumes:
      - ./static:/app/static
      - ./views:/app/views

networks:
  app-network:
    driver: bridge
