version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:8080"  # Usa la variable PORT del archivo .env
    environment:
      PORT: ${PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SQLSERVER_CONNECTION_STRING: ${SQLSERVER_CONNECTION_STRING}
    networks:
      - app-network
    volumes:
      - ./static:/app/static
      - ./views:/app/views
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
