version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SQLSERVER_CONNECTION_STRING=${SQLSERVER_CONNECTION_STRING}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
